import { Button, ComboBox, HorizontalBox, VerticalBox, GridBox } from "std-widgets.slint";

export struct MonitorData {
    title: string,
    image: image
}

component MonitorItem inherits Rectangle {
    callback clicked <=> touch.clicked;

    in property <image> image;
    in-out property <string> title;
    in property <bool> selected;
    
    border-width: selected ? 4px : 2px;
    border-color: selected ? #f1d69b : whitesmoke;
    border-radius: 5px;

    animate border-width {
        duration: 200ms;
        easing: ease-in-out;
    }

    animate border-color {
        duration: 200ms;
        easing: ease-in-out;
    }

    Text {
        x: (parent.width / 2) - (self.width / 2);
        y: 8px;
        text: parent.title;
        overflow: elide;
        max-width: 15px;
        font-size: 14px;
        font-weight: 600;
        color: selected ? #fff2a6 : whitesmoke;
    }

    Image {
        y: 28px;
        source: root.image;
        width: parent.width - 40px;
        height: parent.height - 40px;
    }

    touch := TouchArea {}
}

export component MonitorSelector inherits VerticalBox {
    in-out property <bool> enabled;
    in-out property <int> selected_monitor;
    in-out property <[MonitorData]> monitors_data;

    callback update_monitor_preview(int, image);

    update_monitor_preview(index, image_data) => {
        self.monitors_data[index].image = image_data;
    }

    Text {
        text: "Выберите монитор";
        font-size: 18px;
        font-weight: 600;
        color: whitesmoke;
    }
    HorizontalBox {
        alignment: start;
        
        for monitor[i] in monitors_data: MonitorItem {
            title: monitor.title;
            image: monitor.image;
            selected: selected_monitor == i+1;
            width: 480px;
            height: 300px;
            
            clicked => {
                if enabled {
                    if selected_monitor == i+1 {
                        selected_monitor = 0;
                    } else {
                        selected_monitor = i+1;
                    }
                }
            }
        }
    }
}
